name: Deploy docs to Cloudflare Pages

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build site
        run: mkdocs build -d site
      - name: Install Wrangler
        run: npm install -g wrangler
      - name: Publish to Cloudflare Pages
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          # Requires: CF_API_TOKEN secret and the Cloudflare Pages project connected
          # Set your project name in the secret CF_PROJECT_NAME
          # (or replace below with the actual project name string)
          wrangler pages publish site --project-name "${{ secrets.CF_PROJECT_NAME }}"
